// AUTO-GENERATED from songs.txt by scripts/gen-karaoke-songs.mjs.
// The karaoke catalogue for ראש השנה תשפ״ז.
//
// Ordered by Hebrew collation (artist, then title) with Hebrew songs first and
// English songs after. Numbers are sequential 1..112 and are what guests
// call out loud, so they must stay stable once the list has been shared.

export type SongLang = "he" | "en";

export interface Song {
  /** The number a guest says out loud. Stable, 1-based. */
  n: number;
  artist: string;
  title: string;
  /** Script of the *artist* name — drives the HE/EN filter, not the title. */
  lang: SongLang;
  /** Optional curated badge (e.g. a suggested opener). */
  note?: string;
}

export const SONGS: Song[] = [
  { n: 1, artist: "אברהם טל", title: "הימים עוברים", lang: "he" },
  { n: 2, artist: "אברהם טל", title: "מחוזקים לעולם", lang: "he" },
  { n: 3, artist: "אודיה", title: "אינטלקטוערס", lang: "he" },
  { n: 4, artist: "אודיה", title: "אליס", lang: "he" },
  { n: 5, artist: "אודיה", title: "פאפי", lang: "he" },
  { n: 6, artist: "אייל גולן", title: "כשאחר", lang: "he" },
  { n: 7, artist: "אייל גולן", title: "עיר נמל", lang: "he" },
  { n: 8, artist: "אלה לי", title: "זוט עני", lang: "he" },
  { n: 9, artist: "אלה לי", title: "מה אתה רוצה", lang: "he" },
  { n: 10, artist: "אריק איינשטיין", title: "אני ואתה", lang: "he", note: "שיר פתיחה מומלץ" },
  { n: 11, artist: "אתניקס", title: "ב.מ.וו שחורה", lang: "he" },
  { n: 12, artist: "אתניקס", title: "מחר אני בבית", lang: "he" },
  { n: 13, artist: "אתניקס", title: "ציפור מדבר", lang: "he" },
  { n: 14, artist: "בועז שרעבי", title: "את לי לילה", lang: "he" },
  { n: 15, artist: "בית הבובות", title: "סיגפו", lang: "he" },
  { n: 16, artist: "בנזין", title: "יום שישי", lang: "he" },
  { n: 17, artist: "ברי סחרוף", title: "חלליות", lang: "he" },
  { n: 18, artist: "ג'יין בורדו", title: "עינב", lang: "he" },
  { n: 19, artist: "דודו אהרון", title: "תגידו לה", lang: "he" },
  { n: 20, artist: "דודי בוזגלו", title: "אולי אהיה שמח", lang: "he" },
  { n: 21, artist: "דני סנדרסון", title: "אצל הדודה והדוד", lang: "he" },
  { n: 22, artist: "דני סנדרסון", title: "גלשן", lang: "he" },
  { n: 23, artist: "האולטראס", title: "מסיבה בחיפה", lang: "he" },
  { n: 24, artist: "החלונות הגבוהים", title: "אינך יכולה", lang: "he" },
  { n: 25, artist: "היהודים", title: "מחפש תשובה", lang: "he" },
  { n: 26, artist: "היהודים", title: "עוד ארון אחד", lang: "he" },
  { n: 27, artist: "היהודים", title: "קח אותי", lang: "he" },
  { n: 28, artist: "הפרויקט של רביבו", title: "תן לזמן ללכת", lang: "he" },
  { n: 29, artist: "הראל סקעת", title: "לעוף", lang: "he" },
  { n: 30, artist: "זוהר ארגוב", title: "הפרח בגני", lang: "he" },
  { n: 31, artist: "חמסה", title: "אתה חייב למות עליי", lang: "he" },
  { n: 32, artist: "חנן בן ארי", title: "החיים שלנו תותים", lang: "he" },
  { n: 33, artist: "חנן בן ארי", title: "ויקיפדיה", lang: "he" },
  { n: 34, artist: "חנן בן ארי", title: "עטלף עיוור", lang: "he" },
  { n: 35, artist: "טונה", title: "בסיבוב", lang: "he" },
  { n: 36, artist: "טונה", title: "יא 2", lang: "he" },
  { n: 37, artist: "טונה", title: "סהרה", lang: "he" },
  { n: 38, artist: "טונה", title: "רוק 30", lang: "he" },
  { n: 39, artist: "טיפקס", title: "הרבי ג'ו כפרה", lang: "he" },
  { n: 40, artist: "טיפקס", title: "שלוש בלילה", lang: "he" },
  { n: 41, artist: "יואב יצחק", title: "צלצולי פעמונים", lang: "he" },
  { n: 42, artist: "כוורת", title: "גוליית", lang: "he" },
  { n: 43, artist: "כוורת", title: "יו יה", lang: "he" },
  { n: 44, artist: "כפיר צפריר", title: "פחד אלוהים", lang: "he" },
  { n: 45, artist: "ליאור נרקיס וכנסיית השכל", title: "היינו עושים אהבה", lang: "he" },
  { n: 46, artist: "מאור אדרי", title: "My Name Is Maor Edri", lang: "he" },
  { n: 47, artist: "מאיר בנאי", title: "שער הרחמים", lang: "he" },
  { n: 48, artist: "מוני", title: "דרבק", lang: "he" },
  { n: 49, artist: "מוניקה סקס", title: "מכה אפורה", lang: "he" },
  { n: 50, artist: "מוקי", title: "ילד של אבא", lang: "he" },
  { n: 51, artist: "מוקי", title: "ילדה סוכר", lang: "he" },
  { n: 52, artist: "מוקי", title: "לב חופשי", lang: "he" },
  { n: 53, artist: "מירי מסיקה", title: "אף אחת", lang: "he" },
  { n: 54, artist: "מירי מסיקה", title: "מפחד עלייך", lang: "he" },
  { n: 55, artist: "מירי מסיקה", title: "שיר לשירה", lang: "he" },
  { n: 56, artist: "מרגלית צנעני", title: "נערי שובה אליי", lang: "he" },
  { n: 57, artist: "מרגלית צנעני", title: "עץ ירוק מפלסטיק", lang: "he" },
  { n: 58, artist: "מרסדס בנד", title: "הבלדה למחלקה להלבשה תחתונה", lang: "he" },
  { n: 59, artist: "משה פרץ", title: "ברצלונה", lang: "he" },
  { n: 60, artist: "משינה", title: "אהובתי", lang: "he" },
  { n: 61, artist: "מתן גלילוב", title: "זוכרת", lang: "he" },
  { n: 62, artist: "נוי פדלון", title: "סוודר", lang: "he" },
  { n: 63, artist: "נועה קירל", title: "פאוץ'", lang: "he" },
  { n: 64, artist: "נועה קירל", title: "פנתרה", lang: "he" },
  { n: 65, artist: "נינט טייב", title: "היא יודעת", lang: "he" },
  { n: 66, artist: "נס וסטילה", title: "חרבו דרבו", lang: "he" },
  { n: 67, artist: "נס וסטילה", title: "תיק קטן", lang: "he" },
  { n: 68, artist: "נסרין קדרי", title: "לא לפנות אליי", lang: "he" },
  { n: 69, artist: "נצ'י נצ' (רביד פלוטניק)", title: "כל הזמן הזה", lang: "he" },
  { n: 70, artist: "סאבלימינל והצל", title: "הפינאלי", lang: "he" },
  { n: 71, artist: "סטטיק ובן אל תבורי", title: "כביש החוף", lang: "he" },
  { n: 72, artist: "עדן בן זקן", title: "מלכת השושנים", lang: "he" },
  { n: 73, artist: "עדן בן זקן", title: "רולקס וקסקט", lang: "he" },
  { n: 74, artist: "עדן בן זקן", title: "תגיד לי Je T'aime", lang: "he" },
  { n: 75, artist: "עדן בן זקן", title: "תזיזו", lang: "he" },
  { n: 76, artist: "עוזי חיטמן", title: "נולדתי לשלום", lang: "he" },
  { n: 77, artist: "עומר אדם", title: "טמפרטורה", lang: "he" },
  { n: 78, artist: "עומר אדם", title: "מלכת הדור", lang: "he" },
  { n: 79, artist: "עומר אדם", title: "תל אביב", lang: "he" },
  { n: 80, artist: "עידן רייכל", title: "אהבה כזו", lang: "he" },
  { n: 81, artist: "עילי בוטנר ורן דנקר", title: "שווים", lang: "he" },
  { n: 82, artist: "פאר טסי", title: "38", lang: "he" },
  { n: 83, artist: "פאר טסי", title: "אהבה חולה", lang: "he" },
  { n: 84, artist: "פאר טסי", title: "היא לא יודעת למה", lang: "he" },
  { n: 85, artist: "פאר טסי", title: "משקה יקר", lang: "he" },
  { n: 86, artist: "פאר טסי ואלון דה לוקו", title: "שתיתי", lang: "he" },
  { n: 87, artist: "צביקה פיק", title: "הרקדן האוטומטי", lang: "he" },
  { n: 88, artist: "קרן פלס", title: "באת לי פתאום", lang: "he" },
  { n: 89, artist: "קרן פלס", title: "מבול", lang: "he" },
  { n: 90, artist: "קרן פלס", title: "שקופים", lang: "he" },
  { n: 91, artist: "רוני דואני", title: "סוכריה", lang: "he" },
  { n: 92, artist: "ריקי גל", title: "בני ילד רע", lang: "he" },
  { n: 93, artist: "ריקי גל", title: "לגור איתו", lang: "he" },
  { n: 94, artist: "שב\"ק ס", title: "בוא ונביא לך ת'פאנק", lang: "he" },
  { n: 95, artist: "שב\"ק ס", title: "מכופף הבננות", lang: "he" },
  { n: 96, artist: "שב\"ק ס", title: "נופל וקם", lang: "he" },
  { n: 97, artist: "שב\"ק ס", title: "תתקעו בחצוצרה", lang: "he" },
  { n: 98, artist: "שוטי הנבואה", title: "קול גלגל", lang: "he" },
  { n: 99, artist: "שולי נתן (או נעמי שמר)", title: "ירושלים של זהב", lang: "he", note: "שיר סיום" },
  { n: 100, artist: "שלומי שבת", title: "בראשית עולם", lang: "he" },
  { n: 101, artist: "שלומי שבת", title: "ואני שר", lang: "he" },
  { n: 102, artist: "שלומי שבת", title: "שתדעי", lang: "he" },
  { n: 103, artist: "שלמה ארצי", title: "היא לא יודעת מה עובר עליי", lang: "he" },
  { n: 104, artist: "שלמה ארצי", title: "ירח", lang: "he" },
  { n: 105, artist: "שרית חדד", title: "בחום של תל אביב", lang: "he" },
  { n: 106, artist: "Amy Winehouse", title: "Back To Black", lang: "en" },
  { n: 107, artist: "Amy Winehouse", title: "Valerie", lang: "en" },
  { n: 108, artist: "Backstreet Boys", title: "I Want It That Way", lang: "en" },
  { n: 109, artist: "Britney Spears", title: "Baby One More Time", lang: "en" },
  { n: 110, artist: "Carly Rae Jepsen", title: "Call Me Maybe", lang: "en" },
  { n: 111, artist: "Justin Bieber", title: "Baby", lang: "en" },
  { n: 112, artist: "The Cranberries", title: "Zombie", lang: "en" },
];

export const TOTAL = SONGS.length;
