#!/usr/bin/env node
// Scan the app/ directory for real route folders and write an authoritative
// manifest to app/_lib/routes.generated.ts. Runs automatically before `dev` and
// `build` (npm `predev`/`prebuild` hooks).
//
// Why a build-time manifest instead of scanning at runtime: the owner overview
// (/all) is a dynamic route, and on Vercel a serverless function may not have the
// app/ source files on disk at request time. Generating the list at build time
// and importing it statically is robust everywhere. The /all page diffs this
// list against app/_lib/spaces.ts to flag drift.

import { readdir, writeFile, readFile } from "node:fs/promises";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const APP_DIR = join(ROOT, "app");
const OUT = join(APP_DIR, "_lib", "routes.generated.ts");

const PAGE_FILES = ["page.tsx", "page.jsx", "page.ts", "page.js"];

async function hasPage(dir) {
  let entries;
  try {
    entries = await readdir(dir);
  } catch {
    return false;
  }
  return PAGE_FILES.some((p) => entries.includes(p));
}

async function scan() {
  const entries = await readdir(APP_DIR, { withFileTypes: true });
  const slugs = [];
  for (const e of entries) {
    if (!e.isDirectory()) continue;
    // Skip private folders (_x), route groups ((x)), parallel/intercept (@x, (.)),
    // and dotfiles — none of these are plain public route segments.
    if (/^[_(@.]/.test(e.name)) continue;
    if (await hasPage(join(APP_DIR, e.name))) slugs.push(e.name);
  }
  return slugs.sort();
}

const slugs = await scan();

const body = `// AUTO-GENERATED by scripts/scan-routes.mjs — do not edit by hand.
// Regenerated automatically before \`npm run dev\` and \`npm run build\`.
// The complete list of top-level route segments that have a page in app/.

export const routeSlugs: string[] = [
${slugs.map((s) => `  ${JSON.stringify(s)},`).join("\n")}
];
`;

// Only write when the content actually changes, to avoid needless churn.
let prev = "";
try {
  prev = await readFile(OUT, "utf8");
} catch {
  /* first run */
}
if (prev !== body) {
  await writeFile(OUT, body, "utf8");
  console.log(`scan-routes: wrote ${slugs.length} route(s) → app/_lib/routes.generated.ts`);
} else {
  console.log(`scan-routes: ${slugs.length} route(s), no change`);
}
