// AUTO-GENERATED by scripts/scan-routes.mjs — do not edit by hand.
// Regenerated automatically before `npm run dev` and `npm run build`.
// The complete list of top-level route segments that have a page in app/.

export const routeSlugs: string[] = [
  "all",
  "app-arena",
  "chase-medicine",
  "spaces",
];
